version: '3.8'

services:
  model-api:
    image: ml-model-api:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 4
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=5000"
    volumes:
      - model_api_data:/app  # Mount the volume to /app
    networks:
      - default

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command: --config.file=/etc/prometheus/prometheus.yml
    deploy:
      mode: global
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      mode: global
    networks:
      - default

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    deploy:
      mode: global
    networks:
      - default

volumes:
  grafana_data:
  model_api_data:  # Define the volume

networks:
  default: