global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
        # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]

- job_name: 'node-exporter'
  scrape_interval: 5s
  static_configs:
  # changed from dns_sd_configs to static_configs
  - targets: [ 'host.docker.internal:9101' ] # updated target and port
